from django.conf.urls import include, url

from . import views
from .api import ArticleResource

# create an instance of ArticleResource
article_resource = ArticleResource()


urlpatterns = [
    url(r'^$', views.hello, name='hello'),
    url(r'^all/$', views.articles, name='articles'),
    url(r'get/(?P<article_id>[0-9+])', views.article, name='get_article'),
    url(r'^language/(?P<language>[a-z\-]+)/$', 'article.views.language', name='language'),
    url(r'^create/$', 'article.views.create', name='create'),
    url(r'^like/(?P<article_id>[0-9]+)/$', 'article.views.like_article', name='like_article'),
    url(r'^search/$', 'article.views.search_titles', name='search'),

    # urls are automatically generated by ArticleResource as required
    url(r'^api/', include(article_resource.urls)),
]
